version: '3.8'

services:
  # Dịch vụ cho database MySQL
  database:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: world
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./world.sql:/docker-entrypoint-initdb.d/world.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "database", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s

  # Dịch vụ cho ứng dụng Spring Boot
  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      # Thay đổi cấu hình kết nối database của ứng dụng
      # Tên host là tên của dịch vụ database
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: production
volumes:
  mysql_data: